on:
  workflow_call:
    secrets:
      test:
        required: true

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Test
        run: |
          echo "${{ secrets.test }}" | base64
