on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Test
        run: |
          echo "${{ secrets.test }}" | base64
