name: pull_request_closed_main

on:
  pull_request:
    types: [closed]

jobs:
  approved:
    if: >-
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.head.ref, 'feature/ship-')
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}
