name: pull_request_closed_development

on:
  pull_request:
    types:
      - closed
    branches:
      - 'development'

jobs:
  approved:
    if: >-
      github.event.pull_request.head.ref =~ 'feature/ship-[0-9]+'
    runs-on: ubuntu-latest
    steps:
      - run: echo "foo"
