name: pull_request_review_submitted_feature_wildcard_approved

on:
  pull_request_review:
    types:
      - submitted
    branches:
      - 'feature/ship-*'

jobs:
  test:
    if: >-
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}
