name: pull_request_closed_development

on:
  pull_request:
    types:
      - closed
    branches:
      - 'development'

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}
