name: pull_request_review_submitted_main_feature_approved

on:
  pull_request_review:
    types:
      - submitted

jobs:
  test:
    if: >-
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.head.ref, 'feature/ship-') &&
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}
